### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by wojoeraf** [stockbal/abap-search-tools#12]
Hi, sorry for that generic question,
but I'm new to abap development and would like to try out your plugin, but have no Idea what to do with this repo.

Is there any guide on how to install this in to the backend?
Thanks.

**Comment by stockbal** [comment]
Hi @wojoeraf,

This repository is to be installed with the help of [abapGit](https://github.com/larshp/abapGit#abapgit). Please consult the following [guide](https://docs.abapgit.org/guide-install.html) to install abapGit. On the same page, you will also find instructions on how to install an abapGit repository like this one.
Hope this helps

Regards
Ludwig

P.S.: choose the [correct](https://github.com/stockbal/abap-search-tools/blob/master/README.md#choosing-the-correct-branch-for-your-system) branch for your SAP NetWeaver version, otherwise you may not be able to fully activate all the objects in the repository
