### ISSUE TITLE
ABAP code search is not available in project 

### ISSUE THREAD

**Issue by Shlomon-G** [stockbal/abap-search-tools#18]
Hi there,

I installed the Eclipse ADT plugin and installed the search tools branch nw-740 for our netweaver 7.40 system, got all authorizations for S_ADT_RES and still can't use the plugin. I managed to use it last year, but we copied our prod system to our test system and I can't get it to work anymore. I deleted and pulled the project several times but the strange thing is I get differences for some files and even the remote file gets marked as (M)odified... 
Example: /src/zsat_join_condition_data.tabl.xml
lines 15-19

     <ADMINFIELD>0</ADMINFIELD>
     <INTTYPE>C</INTTYPE>
     -<INTLEN>000002</INTLEN>
     +<INTLEN>000001</INTLEN>
     <DATATYPE>CHAR</DATATYPE>

By the way, it is a non-unicode system.

**Comment by Shlomon-G** [comment]
Clarification: The plugin wasn't part of our production system, i pulled to a "clean" test system without any old search tool files. Nothing to differ or modify...

**Comment by stockbal** [comment]
Hi @Shlomon-G,

First of all, although I do not mention it in any of my abapGit repositories, non-unicode systems are not supported by me, as I do not really have a system like that. So if the root cause of it not working comes from that, I am sorry.

A next point of confusion is the issue title, which sounds to me like you are trying to get my _ABAP Code Search_-Plug-in to run, which is located here [abap-code-search-tools](https://github.com/stockbal/abap-code-search-tools).

If this is not the case and you are indeed trying to install my _ABAP Search and Analysis Tools_-Plug-in, maybe you can provide a bit more information:
- is your abapGit installation up-to-date? 
- are all objects active?
- is the repository free of syntax errors? (Syntax-Check after the pull in abapGit)
- did you check the _ABAP Communication Log_ in eclipse?
![image](https://user-images.githubusercontent.com/35834861/216310519-f1b37a68-dfb0-45a7-b80a-03552982db66.png)

Best regards,
Ludwig

**Comment by Shlomon-G** [comment]
Argh... Well, this explains a lot. I was indeed trying to get the _abap **CODE** search tools_ to work, didn't think (and didn't notice) the same developer created two almost identically named projects... Yeah, the correct project solved the "problem", who could have guessed. Everything else was fine. Sorry!
